LAUNCH_REQUEST = 'LaunchRequest'

AMAZON_YES_INTENT = 'AMAZON.YesIntent'

AMAZON_NO_INTENT = 'AMAZON.NoIntent'

AMAZON_HELP_INTENT = 'AMAZON.HelpIntent'

AMAZON_CANCEL_INTENT = 'AMAZON.CancelIntent'

AMAZON_STOP_INTENT = 'AMAZON.StopIntent'

SESSION_ENDED_REQUEST = 'SessionEndedRequest'
