LAUNCH_REQUEST = 'LaunchRequest'

FIRST_ORDER_INTENT = 'FirstOrderIntent'

SECOND_ORDER_INTENT = 'SecondOrderIntent'

THIRD_ORDER_INTENT = 'ThirdOrderIntent'

AMAZON_YES_INTENT = 'AMAZON.YesIntent'

AMAZON_NO_INTENT = 'AMAZON.NoIntent'

AMAZON_HELP_INTENT = 'AMAZON.HelpIntent'

AMAZON_CANCEL_INTENT = 'AMAZON.CancelIntent'

AMAZON_STOP_INTENT = 'AMAZON.StopIntent'

SESSION_ENDED_REQUEST = 'SessionEndedRequest'
